apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: nagp
spec:
  serviceName: mongodb
  selector:
    matchLabels:
      app: mongodb  
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password                
        volumeMounts:
        - name: mongo-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
     
