apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: nagp
  labels:
    tier: frontend
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: nodeapp
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: surajkishor/nodeapp:1
          envFrom:
          - configMapRef:
              name: mongodb-config
          env:            
            - name: MONGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: user
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
