apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: nagp
spec:
  selector:
    app: nodeapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  # externalIPs: 
  #   - 192.168.0.10
